### PR TITLE
Ensure connect delivers promise on error

### LINKED ISSUE #5: How to handle connection error?
It seems that everything stuck on `<!`
```clojure
(let [stream (<! (ws/connect URL)]
``` 
if the URL is not available.

There is no example in the documentation how to handle connection errors.

### PR DESCRIPTION
**Pull request by ir4y**

### CODE REVIEW

**Comment by ir4y** [comment]
@weavejester This resolves the issue with connecting error for me.

**Comment by weavejester** [comment]
Thanks! Could you add a test and change the commit message to something more descriptive, such as:

    Ensure connect delivers promise on error (fixes #5)

**Comment by ir4y** [comment]
@weavejester I have added tests.

**Comment by ir4y** [comment]
@weavejester when can you merge my changes and do the release?

**Comment by weavejester** [comment]
Sorry, this slipped off my todo list. Is it possible for you to fix the indentation in the test you added? Otherwise I'll need to add in a new formatting commit after the PR is merged. Do that and I'll merge.

**Comment by ir4y** [comment]
@weavejester The indentation is fixed.

**Pull request merged**
